export const STAFF_SIGNIN_REQUEST = "STAFF_SIGNIN_REQUEST";
export const STAFF_SIGNIN_SUCCESS = "STAFF_SIGNIN_SUCCESS";
export const STAFF_SIGNIN_FAIL = "STAFF_SIGNIN_FAIL";
export const STAFF_SIGNOUT = "STAFF_SIGNOUT";

export const STAFF_LIST_REQUEST = "STAF_LIST_REQUEST";
export const STAFF_LIST_SUCCESS = "STAF_LIST_SUCCESS";
export const STAFF_LIST_FAIL = "STAF_LIST_FAIL";

export const STAFF_CREATE_REQUEST = "STAFF_CREATE_REQUEST";
export const STAFF_CREATE_SUCCESS = "STAFF_CREATE_SUCCESS";
export const STAFF_CREATE_FAIL = "STAFF_CREATE_FAIL";
export const STAFF_CREATE_RESET = "STAFF_CREATE_RESET";

export const STAFF_DELETE_REQUEST = "STAFF_DELETE_REQUEST";
export const STAFF_DELETE_SUCCESS = "STAFF_DELETE_SUCCESS";
export const STAFF_DELETE_FAIL = "STAFF_DELETE_FAIL";
export const STAFF_DELETE_RESET = "STAFF_DELETE_RESET";

export const STAFF_UPDATE_REQUEST = "STAFF_UPDATE_REQUEST";
export const STAFF_UPDATE_SUCCESS = "STAFF_UPDATE_SUCCESS";
export const STAFF_UPDATE_FAIL = "STAFF_UPDATE_FAIL";
export const STAFF_UPDATE_RESET = "STAFF_UPDATE_RESET";

export const STAFF_DETAILS_REQUEST = "STAFF_DETAILS_REQUEST";
export const STAFF_DETAILS_SUCCESS = "STAFF_DETAILS_SUCCESS";
export const STAFF_DETAILS_FAIL = "STAFF_DETAILS_FAIL";
export const STAFF_DETAILS_RESET = "STAFF_DETAILS_RESET";
